name: Check for New DEV Interactions and Add to Orbit
on:
  schedule:
    - cron: "20 0 * * *"
  workflow_dispatch:
jobs:
  comments-workflow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Set up Ruby 2.7.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Bundle Install
      run: |
        gem update --system 3.1.4 -N
        gem install --no-document dev_orbit
    - name: Check for New Comments for a Dev user
      run: |
        dev_orbit --check-comments
    - name: Check for New Followers for a Dev user
      run: |
        dev_orbit --check-followers
    - name: Check for new Comments for a Dev Organization
      run: |
        dev_orbit --check-organization-comments
      env:
        DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
        DEV_USERNAME: ${{ secrets.DEV_USERNAME }}
        ORBIT_API_KEY: ${{ secrets.ORBIT_API_KEY }}
        ORBIT_WORKSPACE_ID: ${{ secrets.ORBIT_WORKSPACE_ID }}
